config/routes.rb
Rails.application.routes.draw do

  root 'home#homepage'
  get('/home/contact_us', { :controller => 'home', :action => 'contact_us' })
  get('/people', { :controller => 'home', :action => 'people' })
  get('/people/:id', { :controller => 'home', :action => 'people_home' })
  get('/mitems', { :controller => 'home', :action => 'mitem' })
  get('/searchresults', { :controller => 'home', :action => 'search' })

  get('/offers/new', { :controller => 'offers', :action => 'new' })
  post('/offers', { :controller => 'offers', :action => 'create' })

  get('/items/new', { :controller => 'items', :action => 'new' })
  post('/items', { :controller => 'items', :action => 'create' })

  get('/items', { :controller => 'items', :action => 'index' })
  get('/items/:id', { :controller => 'items', :action => 'show' })

  get('/items/:id/edit', { :controller => 'items', :action => 'edit' })
  patch('/items/:id', { :controller => 'items', :action => 'update' })

  delete('/items/:id', { :controller => 'items', :action => 'destroy' })

  resources :lists

  devise_for :users

end

app/models/item.rb
class Item < ActiveRecord::Base
  after_create :init

  belongs_to :list
  has_many :offers

  def init
    self.status = 0
    self.save
  end

  validates :rating, :presence => true
  validates :description, :presence => true
  validates :title, :presence => true
  validates :list_id, :presence => true

end

app/models/list.rb
class List < ActiveRecord::Base
  after_create :create_token

  has_many :items
  belongs_to :user

  validates :title, :presence => true
  validates :description, :presence => true
  validates :expiration, :presence => true
  validates :privacy, :presence => true, :inclusion => { :in => [1,2]}
  validates :user_id, :presence => true

  def create_token
    self.token = SecureRandom.hex(6)
    self.save
  end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :item
  belongs_to :user

  validates :user, :presence => true
  validates :item, :presence => true
  validates :proportion, :presence => true
  validate :max_one

  def max_one
    if self.proportion > (1 - self.item.status)
      errors.add(:proportion, "Cannot exceed 100% of item value")
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :add_default_list

  def add_default_list
    list = List.new
    list.title = "undecided"
    list.description = "This is a list of undecided items."
    list.expiration = "2099-12-31"
    list.privacy = "2"
    list.user_id = self.id
    list.save
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
  has_many :offers
  has_many :items, :through => :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :avatar_url
    devise_parameter_sanitizer.for(:sign_up) << :username

    devise_parameter_sanitizer.for(:account_update) << :avatar_url
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def homepage
  end

  def contact_us
  end

  def people
    @users = User.all
  end

  def people_home
    @user = User.find(params[:id])
    @lists = @user.lists
  end

  def mitem
    @items = current_user.items
  end

  def search
    @keyword = params[:search]
    @search_result = User.where("username like ?", "%#{@keyword}%")
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new
    @item.list_id = params[:list_id]
    @item.title = params[:title]
    @item.rating = params[:rating]
    @item.store_link = params[:store_link]
    @item.description = params[:description]
    @item.pic = params[:pic]

    if @item.save
      from = params[:from]
      if from == "list"
        redirect_to "/lists/#{@item.list.id}"
      else from == "item"
        redirect_to "/mitems"
      end
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    @item.list_id = params[:list_id]
    @item.title = params[:title]
    @item.rating = params[:rating]
    @item.store_link = params[:store_link]
    @item.description = params[:description]
    @item.pic = params[:pic]

    if @item.save
      # if @item.list_id.present?
      #   redirect_to "/lists/#{@item.list.id}", :notice => "Item updated successfully."
      # else
      #   redirect_to "/items", :notice => "Item updated successfully."
      # end
      redirect_to "/items", :notice => "Item updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy

    redirect_to "/items", :notice => "Item deleted."
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new
    @list.title = params[:title]
    @list.description = params[:description]
    @list.expiration = params[:expiration]
    @list.privacy = params[:privacy]
    @list.user_id = params[:user_id]

    if @list.save
      redirect_to "/lists/#{@list.id}", :notice => "List created successfully."
    else
      render 'new'
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    @list.title = params[:title]
    @list.description = params[:description]
    @list.expiration = params[:expiration]
    @list.privacy = params[:privacy]
    @list.user_id = params[:user_id]

    if @list.save
      redirect_to lists_url, :notice => "List updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])

    @list.destroy

    redirect_to "/people/#{current_user.id}", :notice => "List deleted."
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authorize

  def index
    @offers = Offer.all
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def new
    @offer = Offer.new
    @item = Item.find(params[:item_id])
  end

  def create
    @offer = Offer.new
    @offer.user_id = current_user.id
    @offer.item_id = params[:item_id]

    radio_prop = params[:full_prop]
    if radio_prop == "true"
      @offer.proportion = 1
    else
      @offer.proportion = params[:proportion]
    end

    @item = Item.find(params[:item_id])
    if current_user.id == @item.list.user_id
      redirect_to "/offers/new?item_id=#{@item.id}", :notice => "You are the creator of this Wish List." and return
    end

    if @item.list.token != params[:token]
      redirect_to "/offers/new?item_id=#{@item.id}", :alert => "The token you entered is wrong. If you are not sure, please contact the list creator." and return
    end

    @item.status = @item.status + @offer.proportion

    if @offer.save
      @item.save
      redirect_to "/lists/#{@item.list.id}", :alert => "Offer created successfully."
    else
      render 'new'
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])

    @offer.user_id = params[:user_id]
    @offer.item_id = params[:item_id]
    @offer.proportion = params[:proportion]

    if @offer.save
      redirect_to "/offers", :notice => "Offer updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @offer = Offer.find(params[:id])

    @offer.destroy

    redirect_to "/offers", :notice => "Offer deleted."
  end

  private

  def authorize
    if current_user
    else
      redirect_to "/"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/contact_us.html.erb
<h1>Build this page later</h1>

app/views/home/homepage.html.erb
<div class="row">
  <div class="intro-header">

    <div class="container">

      <div class="row">
        <div class="col-lg-12">
          <div class="intro-message">
            <h1>Share happiness with friends</h1>
            <h3>Share happiness with friends</h3>
            <!-- <hr class="intro-divider"> -->
          </div>
        </div>
      </div>

    </div>
  </div>
  <!-- /.container -->

  <div class="row">
  </div> <!-- /.intro-header -->
  <div class="content-section-a">

    <div class="container">

      <div class="row">
        <div class="col-lg-5 col-sm-6">
          <hr class="section-heading-spacer">
          <div class="clearfix"></div>
          <h2 class="section-heading">###</h2>
          <p class="lead">###</p>
        </div>
        <div class="col-lg-5 col-lg-offset-2 col-sm-6">
          <img class="img-responsive" src="img/ipad.png" alt="">
        </div>
      </div>

    </div>
    <!-- /.container -->

  </div>
  <!-- /.content-section-a -->
</div>

<div class="row">
  <div class="content-section-b">

    <div class="container">

      <div class="row">
        <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
          <hr class="section-heading-spacer">
          <div class="clearfix"></div>
          <h2 class="section-heading">###</h2>
          <p class="lead">#####<a target="_blank" href="#"></a>Later</p>
        </div>
        <div class="col-lg-5 col-sm-pull-6  col-sm-6">
          <img class="img-responsive" src="img/dog.png" alt="">
        </div>
      </div>

    </div>
    <!-- /.container -->

  </div>
  <!-- /.content-section-b -->

  <div class="row">
  </div>
  <div class="content-section-a">

    <div class="container">

      <div class="row">
        <div class="col-lg-5 col-sm-6">
          <hr class="section-heading-spacer">
          <div class="clearfix"></div>
          <h2 class="section-heading">##<br>Later</h2>
          <p class="lead">##later</p>
        </div>
        <div class="col-lg-5 col-lg-offset-2 col-sm-6">
          <img class="img-responsive" src="img/phones.png" alt="">
        </div>
      </div>

    </div>
    <!-- /.container -->

  </div>
  <!-- /.content-section-a -->
</div>

<div class="row">
  <div class="banner">

    <div class="container">

      <div class="row">
        <div class="col-lg-6">
          <h2>##Later</h2>
        </div>
        <div class="col-lg-6">
          <ul class="list-inline banner-social-buttons">
            <li>
              <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
            </li>
          </ul>
        </div>
      </div>

    </div>
    <!-- /.container -->

  </div>
  <!-- /.banner -->
</div>

<div class="row">
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <ul class="list-inline">
            <li>
              <a href="#home">Home</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="#about">About</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="#services">Services</a>
            </li>
            <li class="footer-menu-divider">&sdot;</li>
            <li>
              <a href="#contact">Contact</a>
            </li>
          </ul>
          <p class="copyright text-muted small">Copyright &copy; TimesL 2014. All Rights Reserved</p>
        </div>
      </div>
    </div>
  </footer>
</div>

<style>
  h6 {
    font-family: "Lato","Helvetica Neue",Helvetica,Arial,sans-serif;
    font-weight: 700;
  }

  .lead {
    font-size: 18px;
    font-weight: 400;
  }

  .intro-header {
    padding-bottom: 50px;
    text-align: center;
    color: #f8f8f8;
    background: url(http://hdwallpaper.freehdw.com/0001/nature-landscapes_other_romantic-place_4295.jpg) no-repeat center center;
    background-size: cover;
  }

  .intro-message {
    position: relative;
    padding-top: 20%;
    padding-bottom: 20%;
  }

  .intro-message > h1 {
    margin: 0;
    text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
    font-size: 5em;
  }

  .intro-divider {
    width: 400px;
    border-top: 1px solid #f8f8f8;
    border-bottom: 1px solid rgba(0,0,0,0.2);
  }

  .intro-message > h3 {
    text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
  }

  @media(max-width:767px) {
    .intro-message {
      padding-bottom: 15%;
    }

    .intro-message > h1 {
      font-size: 3em;
    }

    ul.intro-social-buttons > li {
      display: block;
      margin-bottom: 20px;
      padding: 0;
    }

    ul.intro-social-buttons > li:last-child {
      margin-bottom: 0;
    }

    .intro-divider {
      width: 100%;
    }
  }

  .network-name {
    text-transform: uppercase;
    font-size: 14px;
    font-weight: 400;
    letter-spacing: 2px;
  }

  .content-section-a {
    padding: 50px 0;
    background-color: #f8f8f8;
  }

  .content-section-b {
    padding: 50px 0;
    border-top: 1px solid #e7e7e7;
    border-bottom: 1px solid #e7e7e7;
  }

  .section-heading {
    margin-bottom: 30px;
  }

  .section-heading-spacer {
    float: left;
    width: 200px;
    border-top: 3px solid #e7e7e7;
  }

  .banner {
    padding: 100px 0;
    color: #f8f8f8;
    background: url(../img/banner-bg.jpg) no-repeat center center;
    background-size: cover;
  }

  .banner h2 {
    margin: 0;
    text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
    font-size: 3em;
  }

  .banner ul {
    margin-bottom: 0;
  }

  .banner-social-buttons {
    float: right;
    margin-top: 0;
  }

  @media(max-width:1199px) {
    ul.banner-social-buttons {
      float: left;
      margin-top: 15px;
    }
  }

  @media(max-width:767px) {
    .banner h2 {
      margin: 0;
      text-shadow: 2px 2px 3px rgba(0,0,0,0.6);
      font-size: 3em;
    }

    ul.banner-social-buttons > li {
      display: block;
      margin-bottom: 20px;
      padding: 0;
    }

    ul.banner-social-buttons > li:last-child {
      margin-bottom: 0;
    }
  }

  footer {
    padding: 50px 0;
    background-color: #f8f8f8;
  }

  p.copyright {
    margin: 15px 0 0;
  }
</style>

app/views/home/people.html.erb
<ul>
  <% @users.each do |user| %>
  <li><a href="/people/<%= user.id %>"><%= user.email %></a></li>
  <% end %>
</ul>

app/views/home/people_home.html.erb
<% if current_user == @user %>
  <div class="page-header">
    <h1>
      MyLists
      <a href="/lists/new" class="btn btn-lg btn-default"><i class="fa fa-plus"></i>&nbsp; New Wish List</a>
    </h1>
  </div>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Lists (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% if current_user == @user %>
  <% @lists.each do |list| %>
    <div class="col-xs-12 col-sm-6 col-md-4 isotope-item">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><%= list.title.titleize %></h3>
        </div>
        <div class="panel-body">
          <p><%= list.description %></p>
          <dl class="dl-horizontal">
            <dt>Created_at</dt>
            <dd><%= time_ago_in_words(list.created_at.to_date) %></dd>

            <dt>Updated_at</dt>
            <dd><%= time_ago_in_words(list.updated_at.to_date) %></dd>

            <dt>Expiration</dt>
            <dd><%= list.expiration %></dd>

            <% privacy = list.privacy  %>
            <% case privacy  %>
            <% when 1  %>
            <dt>Privacy</dt>
            <dd>Public</dd>

            <dt>Token</dt>
            <dd><%= list.token %></dd>
            <% when 2  %>
            <dt>Privacy</dt>
            <dd>Me only</dd>
            <% end %>
          </dl>
          <div class="btn-group btn-group-justified">
            <a href="/lists/<%= list.id %>" class="btn btn-primary">
              <i class="fa fa-search-plus"></i>
            </a>

            <a href="/lists/<%= list.id %>/edit" class="btn btn-warning">
              <i class="fa fa-edit"></i>
            </a>

            <%= link_to('<i class="fa fa-trash-o"></i>'.html_safe, list_url(list), method: "delete", class: "btn btn-danger", data: {confirm: "Are you sure you want to delete this item?"}) %>
          </div>
        </div>
      </div>
    </div> <!-- isotope-item -->
  <% end %>
<% else %>
    <% @lists.each do |list| %>
    <% if list.privacy == 1 %>
      <div class="col-xs-12 col-sm-6 col-md-4 isotope-item">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= list.title.titleize %></h3>
          </div>
          <div class="panel-body">
            <p><%= list.description %></p>
            <dl class="dl-horizontal">
              <dt>Created_at</dt>
              <dd><%= time_ago_in_words(list.created_at.to_date) %></dd>

              <dt>Updated_at</dt>
              <dd><%= time_ago_in_words(list.updated_at.to_date) %></dd>

              <dt>Expiration</dt>
              <dd><%= list.expiration %></dd>

            </dl>
            <div class="btn-group btn-group-justified">
              <a href="/lists/<%= list.id %>" class="btn btn-primary">
                <i class="fa fa-search-plus">&nbsp; View</i>
              </a>
              <a href="#" class="btn btn-success">
                <i class="fa fa-bookmark">&nbsp; Mark</i>
              </a>
            </div>
          </div>
        </div>
      </div> <!-- isotope-item -->
    <% end %>
  <% end %>
<% end %>
</div> <!-- container -->

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container').isotope({
      itemSelector: '.isotope-item',
      layoutMode: 'masonry',
      filter: function() {
        return qsRegex ? $(this).text().match( qsRegex ) : true;
      }
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<style>
  .dl-horizontal dt{
    text-align: left;
    width: auto;
    padding-left: 1em;
    padding-right: 1em;
  }
  .dl-horizontal dd {
    /*margin-left: 0;*/
    /*padding-left: 1em;*/
  }
</style>

app/views/home/search.html.erb
<% @search_result.each do |result| %>
<p><a href="/people/<%= result.id %>"><%= result.username %></a></p>
<% end %>

app/views/lists/edit.html.erb
<!-- Validation failure messages -->

<% if @list.errors.any? %>
  <% @list.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>


<!-- Simple full-width example -->

<div class="page-header">
  <h3>You are editing list: <small><em><%= @list.title.titleize %></em></small></h3>
</div>

<div class="row">
  <div class="col-md-12">

    <%= form_tag list_url(@list), class: "form-horizontal", method: "patch" do %>
      <!-- Label and input for title -->
      <div class="form-group">
        <label for="title" class="col-sm-2 control-label">
          Title
        </label>
        <div class="col-sm-10">
          <input type="text" id="title" name="title" placeholder="Title" class="form-control" value="<%= @list.title %>">
        </div>
      </div>

      <!-- Label and input for description -->
      <div class="form-group">
        <label for="description" class="col-sm-2 control-label">
          Description
        </label>
        <div class="col-sm-10">
          <textarea id="description" name="description" placeholder="Description" class="form-control" rows="3"><%= @list.description %></textarea>
        </div>
      </div>

      <!-- Label and input for expiration -->
      <div class="form-group">
        <label for="expiration" class="col-sm-2 control-label">
          Expiration
        </label>
        <div class="col-sm-10">
          <input type="text" id="expiration" name="expiration" placeholder="Expiration" class="form-control" value="<%= @list.expiration %>">
        </div>
      </div>

      <!-- Label and input for privacy -->
      <div class="form-group">
        <label for="privacy" class="col-sm-2 control-label">
          Who can see this list
        </label>
        <div class="col-sm-10">
          <%= select_tag :privacy, options_for_select({"Only me"=>2,"Everyone"=>1}, @list.privacy), class: "form-control" %>
        </div>
      </div>

      <!-- Label and input for user_id -->
      <div class="form-group hidden">
        <label for="user_id" class="col-sm-2 control-label">
          User
        </label>
        <div class="col-sm-10">
          <input type="text" id="user_id" name="user_id" placeholder="User" class="form-control" value="<%= @list.user_id %>">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <input type="submit" value="Update List" class="btn btn-warning">
          or
          <a href="/lists/<%= @list.id %>">Cancel</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- End simple full-width example-->

app/views/lists/index.html.erb
<div class="page-header">
  <h1>
    MyLists
    <a href="/lists/new" class="btn btn-lg btn-default"><i class="fa fa-plus"></i>&nbsp; New Wish List</a>
  </h1>
</div>

<div class="row">
  <div class="col-xs-12">
    <input type="text" id="quicksearch" placeholder="Search Lists (start typing)" class="form-control">
  </div>
</div>

<hr>

<div class="row isotope-container">
<% @lists.each do |list| %>
  <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 isotope-item">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= list.title.titleize %></h3>
      </div>
      <div class="panel-body">
        <p><%= list.description %></p>
        <dl class="dl-horizontal">
          <dt>Created_at</dt>
          <dd><%= list.created_at.to_date %></dd>

          <dt>Updated_at</dt>
          <dd><%= list.updated_at.to_date %></dd>

          <dt>Expiration</dt>
          <dd><%= list.expiration %></dd>

          <dt>Privacy</dt>
          <% privacy = list.privacy  %>
          <% case privacy  %>
          <% when 1  %>
            <dd>Public</dd>
          <% when 2  %>
            <dd>Me only</dd>
          <% end %>
        </dl>
        <div class="btn-group btn-group-justified">
          <a href="/lists/<%= list.id %>" class="btn btn-primary">
            <i class="fa fa-search-plus"></i>
          </a>

          <a href="/lists/<%= list.id %>/edit" class="btn btn-warning">
            <i class="fa fa-edit"></i>
          </a>

          <%= link_to('<i class="fa fa-trash-o"></i>'.html_safe, list_url(list), method: "delete", class: "btn btn-danger", data: {confirm: "Are you sure you want to delete this item?"}) %>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- JavaScript for Isotope layout and quicksearch -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>
<script>
  $(function() {
    // quick search regex
    var qsRegex;

    // init Isotope
    var $container = $('.isotope-container').isotope({
      itemSelector: '.isotope-item',
      layoutMode: 'masonry',
      filter: function() {
        return qsRegex ? $(this).text().match( qsRegex ) : true;
      }
    });

    // use value of search field to filter
    var $quicksearch = $('#quicksearch').keyup( debounce( function() {
      qsRegex = new RegExp( $quicksearch.val(), 'gi' );
      $container.isotope();
    }, 200 ) );

  });

  // debounce so filtering doesn't happen every millisecond
  function debounce( fn, threshold ) {
    var timeout;
    return function debounced() {
      if ( timeout ) {
        clearTimeout( timeout );
      }
      function delayed() {
        fn();
        timeout = null;
      }
      timeout = setTimeout( delayed, threshold || 100 );
    }
  }
</script>

<style>
  .dl-horizontal dt{
    text-align: left;
    width: auto;
    padding-left: 1em;
    padding-right: 1em;
  }
  .dl-horizontal dd {
    /*margin-left: 0;*/
    /*padding-left: 1em;*/
  }
</style>

app/views/offers/new.html.erb
<!-- Validation failure messages -->

<% if @offer.errors.any? %>
  <% @offer.errors.full_messages.each do |message| %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= message %>
    </div>
  <% end %>
<% end %>

<!-- Simple full-width example-->

<div class="page-header">
  <div class="alert alert-warning text-center" role="alert">
    Warning! You're making an offer to <a href="/items/<%= @item.id %>" class="alert-link"><%= @item.title %></a> to <em><%= @item.list.user.email %></em>! If not correct, please <a href="#" class="alert-link">click here</a>.
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_tag "/offers", class: "form-horizontal", method: "post" do %>

      <!-- Label and input for item_id -->
      <% if params[:item_id].present? %>
        <input type="hidden" id="item_id" name="item_id" value="<%= params[:item_id] %>">
      <% else %>
        <input type="hidden" id="item_id" name="item_id" value="<%= @offer.item_id %>">
      <% end %>

      <div class="form-group">
        <label for="token" class="col-sm-3 control-label">
          Please enter the token
        </label>
        <div class="col-sm-9">
          <input type="text" name="token" placeholder="It should be 12 characters" class="form-control">
        </div>
      </div>

      <div class="form-group">
        <label for="full_prop" class="col-sm-3 control-label">
          Fund full proportion?
        </label>
        <div class="col-sm-9">
          <input type="radio" name="full_prop" value="true" checked="checked">Yes
          <input type="radio" name="full_prop" value="false">No
        </div>
      </div>

      <!-- Label and input for proportion -->
      <div class="form-group">
        <label for="proportion" class="col-sm-3 control-label">
          Proportion
        </label>
        <div class="col-sm-9">
          <select name ="proportion" class="form-control" value="<%= @offer.proportion %>">
            <option value = 0.05>5%</option>
            <% for i in 1..(1-@item.status)*10-1 %>
              <option value = <%= i/10.0 %>><%= "#{i*10}%" %></option>
            <% end %>
            <option value = <%= 1-@item.status %>>The Rest</option>
          </select>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-3 col-sm-9">
          <input type="submit" value="Create Offer" class="btn btn-success">
          or
          <a href="/lists/<%= @item.list_id %>">Cancel</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- End simple full-width example-->